name: Autobuild
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Npm install
        run: npm ci
      - name: Npm build
        run: npm run build --if-present
      - name: Generate dist files
        run: npm run generate
      - name: List files in the repository
        run: ls ${{ github.workspace }}
