name: Autobuild Callisto
on:
  schedule:
    - cron:  '45 5,10,15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Set project env
        run: mv ${GITHUB_WORKSPACE}/.env.callisto .env
      - name: Npm install and build
        run: |
          npm ci
          npm run build --if-present
      - name: Generate dist files
        run: npm run generate
      - name: Create production artifact
        uses: actions/upload-artifact@v2
        with:
          name: callisto
          path: dist
          retention-days: 1
